### ISSUE TITLE
Browser navigation broken on Extreme Weather tool

### ISSUE THREAD

**Issue by clhenrick** [berkeley-gif/caladapt-website-2021#5] opened 2021-07-30 00:13 UTC
When navigating to the page for the Extreme Weather tool, hitting the browser's back button causes the URL to change but the previous page's content doesn't load.

**Comment by clhenrick** [comment] 2021-07-30 00:15
![](https://github.trello.services/images/mini-trello-icon.png) [Browser navigation broken on Extreme Weather tool](https://trello.com/c/zwhfooYH/30-browser-navigation-broken-on-extreme-weather-tool)

**Comment by mukhtyar** [comment] 2021-08-30 16:20
This was caused by MapBox not finding the map's `Style` object during `onDestroy` in the `VectorLayer` component. Fixed by adding a `getStyle()` check in https://github.com/berkeley-gif/caladapt-website-2021/pull/15

**Closed as completed by mukhtyar** 2021-08-30 16:20 UTC
Labels: bug
